# Spring Datasource Credentials properties template
spring:
  # Datasource
  datasource:
    url:      jdbc:postgresql://<hostname>:<port>/<database name>
    username: <postgres username>
    password: <postgres password>
